- name: Install and configure HAProxy for load balancing with SSL
  hosts: loadbalancer
  become: true
  vars:
    domain_name: "lagitanerie.fr"
    haproxy_ssl_cert: "/etc/ssl/certs/{{ domain_name }}.crt"
    haproxy_ssl_key: "/etc/ssl/private/{{ domain_name }}.key"
    haproxy_ssl_combined: "/etc/haproxy/certs/{{ domain_name }}.pem"

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present

    - name: Create directory for HAProxy SSL certificate
      file:
        path: "/etc/haproxy/certs"
        state: directory
        mode: '0755'

    - name: Combine SSL cert and key
      shell: "cat {{ haproxy_ssl_cert }} {{ haproxy_ssl_key }} > {{ haproxy_ssl_combined }}"

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: Disable and stop Nginx service
      systemd:
        name: nginx
        enabled: no
        state: stopped

    - name: Enable and start HAProxy
      systemd:
        name: haproxy
        enabled: yes
        state: started

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted

