- hosts: HOSTS
  become: true
 
  tasks:
  - name: Install UFW
    apt:
      name: ufw
      state: present
 
  - name: Enable UFW
    ufw:
      state: enabled
      policy: deny
 
  - name: Allow SSH connections
    ufw:
      rule: allow
      port: '22'
      name: OpenSSH
 
  - name: allow http on port 80
    ufw:
      rule: allow
      port: '80'
      proto: tcp
 
  - name: Allow nginx on personalized port 8080
    ufw:
      rule: allow
      port: '8080'
      proto: tcp
 
  - name: allow https on port 443
    ufw:
      rule: allow
      port: '443'
      proto: tcp
